name: MoeInfo
main: cn.whiteg.moeInfo.MoeInfo
version: 1.1
author: MoeWhite
api-version: 1.15
depend: [  ]
softdepend: [ MMOCore,Vault, MarriageMaster, MoeTP, Multiverse-Core, MoeEco, Residence, PlaceholderAPI, MoePacketAPI, MemFree ]
commands:
  moeinfo:
    description: MyPlug
    aliases: [ mi, moi ]
  prefix:
    description: prefix
    aliases: [ pf ]

  suffix:
    description: Suffix
    aliases: [ sf ]

  namecolour:
    description: NameColour
    aliases: [ nc ]

  whois:
    description: Whois Command

  mute:
    description: Mute Command